#!/usr/bin/env python3
"""
Unit test for the getSpecFromDir fix for auto-generated packages.
"""

import unittest
import os
import sys
import tempfile
from collections import OrderedDict
from unittest.mock import patch

# Add the bits_helpers to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from bits_helpers.utilities import getSpecFromDir, getGeneratedPackages

class TestGetSpecFromDirAutoGenerated(unittest.TestCase):
    """Test cases for getSpecFromDir with auto-generated packages."""
    
    def setUp(self):
        """Set up temporary directories for testing."""
        self.temp_dir = tempfile.mkdtemp()
        self.config_dir = os.path.join(self.temp_dir, "config")
        os.makedirs(self.config_dir)
        self.pkg_dir = os.path.join(self.config_dir, "autogen")
        os.makedirs(self.pkg_dir)
        
        # Set environment variable
        self.old_bits_repo_dir = os.environ.get("BITS_REPO_DIR")
        os.environ["BITS_REPO_DIR"] = self.temp_dir
    
    def tearDown(self):
        """Clean up temporary directories."""
        import shutil
        shutil.rmtree(self.temp_dir)
        
        # Restore environment variable
        if self.old_bits_repo_dir is not None:
            os.environ["BITS_REPO_DIR"] = self.old_bits_repo_dir
        else:
            os.environ.pop("BITS_REPO_DIR", None)
    
    def test_autogenerated_package_without_separator(self):
        """Test getSpecFromDir with auto-generated package that has no '---' separator."""
        # Create a packages.py that generates a package with only header
        packages_py = os.path.join(self.pkg_dir, "packages.py")
        with open(packages_py, 'w') as f:
            f.write('''
def getPackages(pkgs, pkgdir):
    pkgs["testpkg"] = {
        "command": "echo 'package: testpkg\\nversion: v1.0\\ntag: v1.0'",
        "version": "v1.0",
        "pkgdir": pkgdir
    }
''')
        
        # Create a spec that uses "from" to inherit from the auto-generated package
        override_spec = OrderedDict([
            ("package", "testpkg"),
            ("from", "autogen"),
            ("version", "v2.0")
        ])
        
        # This should work without throwing an exception
        result = getSpecFromDir(override_spec, "testpkg", self.config_dir)
        
        # Verify the result
        self.assertEqual(result.get("package"), "testpkg")
        self.assertEqual(result.get("version"), "v2.0")  # Override should be applied
        self.assertEqual(result.get("tag"), "v1.0")  # Base should be inherited
    
    def test_autogenerated_package_with_separator(self):
        """Test getSpecFromDir with auto-generated package that has '---' separator."""
        # Create a packages.py that generates a package with header and body
        packages_py = os.path.join(self.pkg_dir, "packages.py")
        with open(packages_py, 'w') as f:
            f.write('''
def getPackages(pkgs, pkgdir):
    pkgs["testpkg2"] = {
        "command": "echo 'package: testpkg2\\nversion: v1.0\\n---\\necho \\"Building package\\"'",
        "version": "v1.0",
        "pkgdir": pkgdir
    }
''')
        
        # Create a spec that uses "from" to inherit from the auto-generated package
        override_spec = OrderedDict([
            ("package", "testpkg2"),
            ("from", "autogen"),
            ("version", "v2.0")
        ])
        
        # This should work with packages that have "---" separator
        result = getSpecFromDir(override_spec, "testpkg2", self.config_dir)
        
        # Verify the result
        self.assertEqual(result.get("package"), "testpkg2")
        self.assertEqual(result.get("version"), "v2.0")  # Override should be applied

if __name__ == '__main__':
    unittest.main()